### ISSUE TITLE
Question about Manager:execute()

### ISSUE THREAD

**Issue by jblotus** [mfn/php-transaction-manager#1]
Hi there, first of all I love this idea and I'm evaluating it at work to replace our deeply nested transaction issues. I had a question about the Manager::execute() callback. This call seems to only work if you successfully complete the transaction - If an exception or error is thrown we need to wrap it in a try catch:

```php
try {
  $result = $manager->execute(function () {
    //done
  });
} catch (\Exception $ex) {
  //fail
} catch (\Throwable $ex) {
  //fail
}
```

Since this would be a common use case I'm trying to find a reason to actually pass something in to the execute method (since the code is blocking). I would probably end up writing something like this:

```php
try {
  $result = $manager->execute();
  done();
} catch (\Exception $ex) {
  //fail
}
```

Would it make sense to not re-throw the Exception and pass some callbacks instead?

```php
$result = $manager->execute(function() {
  //success
}, function(\Throwable $e, TransactionInterface $offendingTransaction) {
  //fail
}, function() {
  //always
});
```

Just thinking out loud here. Thanks for your time!

**Comment by mfn** [comment]
Hey, first issue, that's wort a ⭐ :-)

I never thought about adding more callbacks (your example looks Promise-esque), as I'm fine using the existing exception mechanism with catching/finally to do this. At least that's what we're doing in my company.

What I did (using Laravel) was defining a `AppTransaction` like this:
```PHP
class AppTransaction
{
    protected $manager;
    public function __construct(Application $app)
    {
        $this->manager = $app->make(Manager::class, [
                $app->make(TransactionBag::class)
                    ->add($app->make(DbTransactionMain::class))
                    ->add($app->make(DbTransactionPostgres::class))
                    ->add($app->make(JobBagTransaction::class)),
            ]
        );
    }
    public function execute(Closure $callback)
    {
        return $this->manager->execute($callback);
    }
}
```
and just passing through whatever `$callback` I have.

I'm fine with extending the `execute` to take more callbacks, optional ones, as long as the default behaviour doesn't change and it's covered with tests :)

It would probably make sense to have default callbacks "emulating" the current behavior.

**Comment by jblotus** [comment]
I'm not personally a fan of the callbacks at all for my use case - I'm thinking I can just avoid passing a callback to execute() and everything will be fine i,e

```php
try {
  $manager->execute();
  doMoreStuff();
  doEvenMoreStuff();
} catch (\Exception $ex) {
  //fail
} catch (\Throwable $ex) {
  //fail
}
```
